-- migrate:up
CREATE TABLE product_options (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name INT NOT NULL,
  stock INT NULL,
  product_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

-- migrate:down
DROP TABLE product_options;

